name: Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Install Dependencies
        run: composer install

      # This is the safest way to handle a multi-line secret
      - name: Create Private Key File
        env:
          MY_PRIVATE_KEY: ${{ secrets.OCI_PRIVATE_KEY }}
        run: |
          echo "$MY_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

      - name: Run oci-arm-host-capacity
        run: php index.php
        env:
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_USER_ID: ${{ secrets.OCI_USER_ID }}
          OCI_TENANCY_ID: ${{ secrets.OCI_TENANCY_ID }}
          OCI_KEY_FINGERPRINT: ${{ secrets.OCI_KEY_FINGERPRINT }}
          OCI_PRIVATE_KEY: ./private_key.pem
          OCI_PRIVATE_KEY_FILENAME: ./private_key.pem
          OCI_PRIVATE_KEY_PASSPHRASE: ""
          OCI_SUBNET_ID: ${{ secrets.OCI_SUBNET_ID }}
          OCI_IMAGE_ID: ${{ secrets.OCI_IMAGE_ID }}
          OCI_SSH_PUBLIC_KEY: ${{ secrets.OCI_SSH_PUBLIC_KEY }}
          OCI_OCPUS: ${{ secrets.OCI_OCPUS }}
          OCI_MEMORY_IN_GBS: ${{ secrets.OCI_MEMORY_IN_GBS }}
